on:
  push:
    branches:
      - patch-1
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ruby
          package-name: release-please-action
          token: ${{ secrets.XXX }}
          default-branch: master
